apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/carmit246/test-gha.git'
    path: argo-test/app1
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      ignoreMissingValueFiles: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true