name: Helm ci
on:
  push:
    paths:
    - 'argo-test/**'
    - '.github/**'

jobs:
  find-charts:
    runs-on: ubuntu-latest
    outputs: 
      CHARTS_TO_BUILD: ${{ steps.find-charts.outputs.CHARTS_TO_BUILD }} 
    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: check for changes
      id: find-charts
      run: |
        git fetch origin
        git remote set-url origin ithub.com:carmit246/test-gha
        FOLDERS=("argo-test/app1" "argo-test/app2")
        for folder in $FOLDERS; do
          git diff --quiet --name-only HEAD HEAD~1 $folder| sed 's/ci-cd\///'| sed 's/\/.*//'
          res=$(git diff --quiet--name-only argo-test| sed 's/argo-test\///'| sed 's/\/.*//')
          if [[ $res ]];then
            echo "changed: " $res
            CHARTS_TO_BUILD+=($folder)
          done
        done
        git diff --name-only HEAD HEAD~1 argo-test| sed 's/argo-test\///'| sed 's/\/.*//'
        echo "CHARTS_TO_BUILD=${CHARTS}" >> $GITHUB_OUTPUT
  
  package-chart:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ needs.find-charts.output.CHARTS_TO_BUILD }}
    steps:
    - name: increment version
      shell: bash
      run: |
        current_version=$(grep -Po "version: \d*.\K(\d)*(?=\d*)" argo-test/app1/Chart.yaml)
        echo $current_version
        new_version=$((current_version+1))
        message=="current_version=$current_version new_version=$new_version"
        echo "$message"
        sed -i "s/^version: .*/version: 0.$new_version.0/" argo-test/app1/Chart.yaml
        git config --global user.email "test@test.com"
        git config --global user.name "test"
        git add argo-test/app1/Chart.yaml
        git commit -m "$message"
        git push
    
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: "3.9.0"
    
    - name: package release
      shell: bash
      run: |
        helm package argo-test/app1
        ls -l