name: Helm ci
on:
  push:
    paths:
    - 'argo-test/app1/**'
    - '.github/**'

jobs:
  helm-ci:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: check for changes
      run: |
        git fetch origin
        git remote set-url origin git@github.com/carmit246
        git diff --name-only HEAD HEAD~1 argo-test| sed 's/argo-test\///'| sed 's/\/.*//'
        CHARTS=$(git diff --name-only argo-test| sed 's/argo-test\///'| sed 's/\/.*//')
        echo "charts=${CHARTS}" >> $GITHUB_OUTPUT

    - name: increment version
      shell: bash
      run: |
        current_version=$(grep -Po "version: \d*.\K(\d)*(?=\d*)" argo-test/app1/Chart.yaml)
        echo $current_version
        new_version=$((current_version+1))
        message=="current_version=$current_version new_version=$new_version"
        echo "$message"
        sed -i "s/^version: .*/version: 0.$new_version.0/" argo-test/app1/Chart.yaml
        git config --global user.email "test@test.com"
        git config --global user.name "test"
        git add argo-test/app1/Chart.yaml
        git commit -m "$message"
        git push
    
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: "3.9.0"
    
    - name: package release
      shell: bash
      run: |
        helm package argo-test/app1
        ls -l