name: add version
on:
  workflow_dispatch:

jobs:
  version-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Python v3.8
      uses: actions/setup-python@v4.3.0
      with:
        python-version: 3.80
    - name: Setup Python dependencies
      run: pip install bump2version==1.0.1
    - name: Upgrade version
      run: |
          git config --global user.email "carmitbe1@gmail.com"
          git config --global user.name "carmitdanon246"
          bump2version patch
    - name: Push new version commit
      run: git push
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: get-envs
      id: get-envs
      run: |
           env
           echo $GITHUB_RUN_NUMBER
           MYSHELL=`echo $GITHUB_RUN_NUMBER| sed s/GITHUB_RUN_NUMBER=//| tr '\n' ' '`
           echo "SHELL:${MYSHELL}" >> $GITHUB_OUTPUT
    - name: get-output
      run: echo ${{ env.get-envs.outputs.MYSHELL }}
    
