name: add version

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo first test
    - uses: actions/checkout@v3
    - name: Use Python v3.8
      uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.8

      - name: Setup Python dependencies
        run: pip install bump2version==1.0.1

      - name: Upgrade version
        run: bump2version patch --dry-run --list
